FROM node:20-alpine AS client-dev
WORKDIR /app
COPY package.json package-lock.json ./
COPY ttl_client/package.json ttl_client/package.json
RUN npm ci --workspaces --include-workspace-root
COPY . .
EXPOSE 5173
CMD ["npm","run","-w","ttl_client","dev"]

