services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ttl
      POSTGRES_PASSWORD: ttl
      POSTGRES_DB: ttl
      TZ: Europe/Amsterdam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ttl -d ttl"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  server:
    build: { context: ./ttl_server, dockerfile: Dockerfile.dev }
    env_file: .env
    environment:
      NODE_ENV: development
      TZ: Europe/Amsterdam
    depends_on:
      db: { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./ttl_server:/app
      - /app/node_modules
    command: npm run dev
    expose: ["3000"]

  client:
    build: { context: ., dockerfile: ttl_client/Dockerfile.dev }
    env_file: .env
    environment:
      NODE_ENV: development
      TZ: Europe/Amsterdam
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      server: { condition: service_healthy }
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173/api/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./ttl_client:/app
      - /app/node_modules
    command: ["npm","run","-w","ttl_client","dev"]
    ports: ["5173:5173"]

  adminer:
    image: adminer:4
    depends_on:
      db: { condition: service_healthy }
    ports: ["8080:8080"]

volumes:
  pgdata:
